---
title: "EFA Personality Item"
author: "Greta Kurpicz"
date: "29 7 2020"
output: html_document
---

```{r setup, include=FALSE}
### ITEM ANALYSIS ###

library(rio)
library(tidyverse)

## Import ## ----
tipi_items <- import(here::here("1_Data","tipi_items.csv"))
ipip_items <- import(here::here("1_Data","ipip_items.csv"))
bfiS_items <- import(here::here("1_Data","bfiS_items.csv"))
bfi10_items <- import(here::here("1_Data","bfi10_items.csv"))

#### I N T E R C O R R E L A T I O N #### ----
library(Hmisc)
library(corrplot)

# Removing age and dataset
tipi <- tipi_items %>% select(!dataset & !age)
# Correlation
tipi_items_corr <- cor(tipi)
tipi_items_corr

# Create Matrix
tipi_matrix_corr <- rcorr(as.matrix(tipi))
tipi_matrix_corr

# Creating plot
corrplot(tipi_items_corr, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)



### F A C T O R   A N A L Y S I S ## ----
# TIPI - Exploratory Factor Analysis#

#PCA for amount of factors
tipi_pca <- princomp(tipi)
summary(tipi_pca)
plot(tipi_pca)

#Factor analysis with 5 factors
tipi_fact5 <- factanal(tipi, factors = 5, rotation = "varimax")


# IPIP - Exploratory Factor Analysis #

# Removing age and dataset
ipip <- ipip_items %>% select(!dataset & !age)

#Factor analysis with 5 factors
ipip_fac <- factanal(ipip, factors = 5, rotation = "varimax")
ipip_fac

# BFI 10 #

# Removing age and dataset
bfi10 <- bfi10_items %>% select(!dataset & !age)

#PCA for amount of factors
bfi10_pca <- princomp(bfi10)
summary(bfi10_pca)
plot(bfi10_pca)

#Factor analysis with 5 factors
bfi10_fac <- factanal(bfi10, factors = 5, rotation = "varimax")
bfi10_fac


# BFI S #

# Removing age and dataset
bfiS <- bfiS_items %>% select(!dataset & !age)

#PCA for amount of factors
bfiS_pca <- princomp(bfiS)
summary(bfiS_pca)
plot(bfiS_pca)

#Factor analysis with 5 factors
bfiS_fac <- factanal(bfiS, factors = 5, rotation = "varimax")
bfiS_fac

```

## TIPI

2 Items per Dimension (Openness, Conscientiousness, Extraversion, Agreeableness, Neuroticism), total 10 items.

Factor Analysis for 5 factors:

```{r}
tipi_fact5 <- factanal(tipi, factors = 5, rotation = "varimax")
tipi_fact5
```

## IPIP

10 Items per Dimension, total 50 items.

Factor Analysis for 5 factors:

```{r}
ipip_fac <- factanal(ipip, factors = 5, rotation = "varimax")
ipip_fac

```

## BFI-10

2 Items per Dimension, total 10 items.

Factor Analysis for 5 factors:

```{r}
bfi10_fac <- factanal(bfi10, factors = 5, rotation = "varimax")
bfi10_fac
```

## BFI-S

3 Items per Dimension, total 15 items.

Factor Analysis for 5 factors:

```{r}
bfiS_fac <- factanal(bfiS, factors = 5, rotation = "varimax")
bfiS_fac
```

